import { SpaceId, ProjectSpace, AppId, AppStatus, AppConfig, DccExtension, ArtAsset, AssetCategory } from './types';

export const PROJECT_SPACES: ProjectSpace[] = [
  {
    id: SpaceId.ProjectA,
    name: '三国：冰河时代',
    extensionCount: 22,
    assetCount: 100,
    description: '主打高精写实次世代角色与手绘场景，包含主包、外包素材和常用管线插件。'
  },
  {
    id: SpaceId.ProjectB,
    name: '项目空间 B (赛博朋克动作)',
    extensionCount: 0,
    assetCount: 0,
    description: '极度科幻、机械体模型、霓虹街区场景美术资产仓库。V1 暂无内容。'
  },
  {
    id: SpaceId.Shared,
    name: '全员共享空间',
    extensionCount: 0,
    assetCount: 0,
    description: '跨项目通用的底层引擎插件、公共资产、规范说明等。V1 暂无内容。'
  },
  {
    id: SpaceId.Personal,
    name: '慕也的个人空间',
    extensionCount: 0,
    assetCount: 0,
    description: '每位美术师的专属云盘，用于存放草稿、个人资产与偏好工具。V1 暂无内容。'
  }
];

export const INITIAL_APPS: AppConfig[] = [
  {
    id: AppId.ComfyUI,
    name: 'ComfyUI',
    isPlatformHosted: true,
    status: AppStatus.NotReady,
    version: 'v1.4.0',
    newVersion: 'v1.6.2', // Handles corner purple badge "有新版本"
    diskRequiredGB: 15,
    sizeGB: 15,
    installPath: ''
  },
  {
    id: AppId.Blender,
    name: 'Blender',
    isPlatformHosted: true,
    status: AppStatus.InstalledOffline,
    version: 'v4.1.0',
    newVersion: 'v4.2.0', // corner purple badge
    diskRequiredGB: 4,
    sizeGB: 4.2,
    installPath: 'C:\\Program Files\\ArtPlatform\\managed\\blender'
  },
  {
    id: AppId.Photoshop,
    name: 'Adobe Photoshop',
    isPlatformHosted: false,
    status: AppStatus.InstalledOffline,
    version: '2024 (v25.0)',
    isOld: true, // orange "版本过旧" badge F4
    diskRequiredGB: 5,
    sizeGB: 4.8,
    installPath: 'C:\\Program Files\\Adobe\\Adobe Photoshop 2024'
  },
  {
    id: AppId.Maya,
    name: 'Autodesk Maya',
    isPlatformHosted: false,
    status: AppStatus.InstalledOffline,
    version: '2024.1',
    diskRequiredGB: 8,
    sizeGB: 7.5,
    installPath: 'C:\\Program Files\\Autodesk\\Maya2024'
  },
  {
    id: AppId.Max3ds,
    name: 'Autodesk 3ds Max',
    isPlatformHosted: false,
    status: AppStatus.NotReady, // To demonstrate manual validation
    version: '2025.0',
    isOld: true,
    diskRequiredGB: 10,
    sizeGB: 9.2,
    installPath: ''
  }
];

// 22 extensions in Project A (we show a subset but label with counts)
export const EXTENSIONS_PROJECT_A: DccExtension[] = [
  {
    id: 'ext-01',
    name: 'L36-Scene Generator',
    dccId: AppId.ComfyUI,
    version: 'v2.1',
    desc: '基于项目Lora的自动高精场景参考图生成节点，集成风格遮罩，加速初期概念迭代。',
    author: 'TA_Guanyu',
    installed: false,
    needsRestart: true,
    isActivated: false
  },
  {
    id: 'ext-02',
    name: 'Auto-UV Unwrapper',
    dccId: AppId.Blender,
    version: 'v1.3.2',
    desc: '次世代角色硬表面一键UV拆解并自动排布，支持多象限UDIM分块。',
    author: 'TA_LaoLi',
    installed: true,
    needsRestart: false,
    isActivated: true
  },
  {
    id: 'ext-03',
    name: 'Sangokuo Character Lora',
    dccId: AppId.ComfyUI,
    version: 'v3.0',
    desc: '三国武将重彩水墨风大模型微调权重，用于 ComfyUI 原画细化。',
    author: 'AI_Studio',
    installed: false,
    needsRestart: true,
    isActivated: false
  },
  {
    id: 'ext-04',
    name: 'Maya Rigging Helper',
    dccId: AppId.Maya,
    version: 'v2.5',
    desc: '一键自动四足与人形骨架搭接工具，适配项目A专属动画状态机。',
    author: 'AnimTech_Z',
    installed: false,
    needsRestart: false,
    isActivated: false
  },
  {
    id: 'ext-05',
    name: 'Smart Exporter',
    dccId: AppId.Maya,
    version: 'v4.0',
    desc: '将模型、蒙皮与关节动画一键导出为游戏引擎优化格式，自动清理命名空间。',
    author: 'TA_Guanyu',
    installed: true,
    needsRestart: false,
    isActivated: true
  },
  {
    id: 'ext-06',
    name: 'PS Texture Sync Node',
    dccId: AppId.Photoshop,
    version: 'v2.1',
    desc: 'Photoshop 绘制贴图实时双向同步投影至 DCC 表面，打通绘制闭环。',
    author: 'IT_TechDept',
    installed: false,
    needsRestart: true,
    isActivated: false
  },
  {
    id: 'ext-07',
    name: 'Vertex Color Baker',
    dccId: AppId.Max3ds,
    version: 'v1.1',
    desc: '烘焙手绘光影至顶点色/自发光，适配轻量化高效率手绘渲染管线。',
    author: 'TA_LaoLi',
    installed: false,
    needsRestart: false,
    isActivated: false
  },
  {
    id: 'ext-08',
    name: 'PBR Material Manager',
    dccId: AppId.Blender,
    version: 'v2.2.1',
    desc: '快速从项目 A PBR库拉取标准的次世代材质，包含金属、软皮革、铠甲、半透明丝绸。',
    author: 'TA_ArtLead',
    installed: false,
    needsRestart: true,
    isActivated: false
  },
  {
    id: 'ext-09',
    name: 'Animate Optimizer',
    dccId: AppId.Maya,
    version: 'v1.8',
    desc: '动画曲线帧数精简、抖动平滑、双脚触地滑脚自动检测修正工具。',
    author: 'Anim_Jie',
    installed: false,
    needsRestart: false,
    isActivated: false
  },
  {
    id: 'ext-10',
    name: 'ComfyUI ControlNet FaceFix',
    dccId: AppId.ComfyUI,
    version: 'v1.0.4',
    desc: '针对写实东方角色五官及神情进行二次高精修复重绘的插件节点。',
    author: 'AI_Studio',
    installed: true,
    needsRestart: true,
    isActivated: false // Needs restart still
  }
];

// Art assets for Project Space A (contains multiple categories to match matrix)
export const ART_ASSETS_PROJECT_A: ArtAsset[] = [
  {
    id: 'asset-01',
    name: '【武将】赵云次世代全身盔甲设计',
    category: AssetCategory.CharConcept,
    format: 'PNG',
    sizeMB: 15.4,
    thumbnail: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1000&auto=format&fit=crop&q=80',
    author: '2D_Lead_Zhao',
    platform: '美术资源库V2',
    desc: '赵云在【长坂坡】战役中的白马银枪盔甲高精原画切图。包含雕花纹路细节、高光流向划分图，供模型师参考。',
    tags: ['角色', '原画', '写实', '盔甲', '主包']
  },
  {
    id: 'asset-02',
    name: '【武器】青龙偃月刀高模文件',
    category: AssetCategory.CharModel,
    format: 'FBX',
    sizeMB: 145.2,
    thumbnail: 'https://images.unsplash.com/photo-1595152772835-219674b2a8a6?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1595152772835-219674b2a8a6?w=1000&auto=format&fit=crop&q=80',
    author: 'Model_TA_Li',
    platform: 'DCC共享端',
    desc: '青龙偃月刀重雕花主武器FBX。Subdivision流程高模，包含700万多边形，细节已雕刻，含置换贴图与高光贴图。',
    tags: ['模型', '武器', '高模', '次世代', '关羽']
  },
  {
    id: 'asset-03',
    name: '【场景】赤壁江河古战场地形 Blender 源文件',
    category: AssetCategory.SceneModel,
    format: 'blend',
    sizeMB: 384.0,
    thumbnail: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1000&auto=format&fit=crop&q=80',
    author: 'Scene_Art_Wang',
    platform: 'DCC共享端',
    desc: '赤壁大战背景山体、江河波浪、沉船残骸的地形网格总合文件。预设好节点材质及动态波形效果。',
    tags: ['场景', 'Blender', '赤壁', '地形', '大场景']
  },
  {
    id: 'asset-04',
    name: '【动作】武将长枪蓄力横扫刺击循环序列',
    category: AssetCategory.Animation,
    format: 'FBX',
    sizeMB: 18.2,
    thumbnail: 'https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=1000&auto=format&fit=crop&q=80',
    author: 'Anim_Studio_A',
    platform: 'IT动画源文件',
    desc: '项目通用人形长枪类武将蓄力挑刺横扫一段。已做好肢体自接触、重力感惯性动画曲线。',
    tags: ['动画', '动作', '长枪', '战斗']
  },
  {
    id: 'asset-05',
    name: '【场景】洛阳宫殿大殿概念设计图',
    category: AssetCategory.SceneConcept,
    format: 'JPG',
    sizeMB: 12.8,
    thumbnail: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1000&auto=format&fit=crop&q=80',
    author: '2D_Env_Zhang',
    platform: '美术资源库V2',
    desc: '洛阳皇宫主殿、汉代雕梁以及龙椅处的正视概念大图。预留好烛光气氛、帷幔流体力学动效参考。',
    tags: ['场景', '原画', '气氛图', '洛阳', '汉代']
  },
  {
    id: 'asset-06',
    name: '【动画】战马踏行涉水重力动效 Maya 源文件',
    category: AssetCategory.Animation,
    format: 'ma',
    sizeMB: 34.5,
    thumbnail: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=1000&auto=format&fit=crop&q=80',
    author: 'AnimTech_Yuan',
    platform: 'IT动画源文件',
    desc: '带缰绳、马鞍和软体肌肉碰撞运算的战马跑动物理测试工程档。可导入Maya直接关联原画骨骼。',
    tags: ['动画', 'Maya', '战马', '涉水', '物理蒙皮']
  },
  {
    id: 'asset-07',
    name: '【主UI】国潮武侠风界面框架九宫格切图',
    category: AssetCategory.GUI,
    format: 'PNG',
    sizeMB: 5.6,
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1000&auto=format&fit=crop&q=80',
    author: 'GUI_Sun',
    platform: 'GUI规范输出库',
    desc: '中国传统重金属金镶玉UI边框。已经配置好九宫格拉伸参数。',
    tags: ['GUI', '界面', '国潮', '切图', '主UI']
  },
  {
    id: 'asset-08',
    name: '【特效】重击碎裂雷电技能粒子序列视频',
    category: AssetCategory.Video,
    format: 'MP4',
    sizeMB: 94.0,
    thumbnail: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=1000&auto=format&fit=crop&q=80',
    author: 'VFX_LaoXie',
    platform: '特效序列中心',
    desc: '武将大招附带闪电碎石砸落的法线通道动画预览视频，支持 ComfyUI 输入节点获取。',
    tags: ['特效', '视频', '闪电', '大招']
  },
  {
    id: 'asset-09',
    name: '【场景】中式古风瓦片高解像度 PBR 材质',
    category: AssetCategory.SceneModel,
    format: 'OBJ',
    sizeMB: 78.4,
    thumbnail: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1000&auto=format&fit=crop&q=80',
    author: 'Model_TA_Li',
    platform: 'DCC共享端',
    desc: '中式古建青砖灰瓦物理材质高模。支持各大DCC导入并快速拼合表面纹理。',
    tags: ['场景', 'PBR', 'OBJ', '中式建筑']
  },
  {
    id: 'asset-10',
    name: '【角色】弓箭手黄忠低模网格与UV图',
    category: AssetCategory.CharModel,
    format: 'FBX',
    sizeMB: 48.2,
    thumbnail: 'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=1000&auto=format&fit=crop&q=80',
    author: 'Model_A_Chen',
    platform: 'DCC共享端',
    desc: '黄忠弓箭手拓扑优化后的低模。包体控制在25000角面数量以下，已排好UV贴图象限。',
    tags: ['模型', '角色', '低模', '黄忠', '网格']
  },
  {
    id: 'asset-11',
    name: '【角色】关羽墨绿重彩次世代原画设计',
    category: AssetCategory.CharConcept,
    format: 'PNG',
    sizeMB: 18.6,
    thumbnail: 'https://images.unsplash.com/photo-1549490349-8643362247b5?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1549490349-8643362247b5?w=1000&auto=format&fit=crop&q=80',
    author: '2D_Lead_Zhao',
    platform: '美术资源库V2',
    desc: '美髯公关羽之绿袍暗花立身展示图及五官细化草案，供3D雕雕刻师制作参考。',
    tags: ['角色', '原画', '重彩', '关羽', '主包']
  },
  {
    id: 'asset-12',
    name: '【场景】华容道险峻泥泞峡谷环境概念图',
    category: AssetCategory.SceneConcept,
    format: 'JPG',
    sizeMB: 22.4,
    thumbnail: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1000&auto=format&fit=crop&q=80',
    author: '2D_Env_Zhang',
    platform: '美术资源库V2',
    desc: '华容道战败撤退概念气氛。主打烂泥横陈、两侧刀削一般峭壁及极小天空视域的表现。',
    tags: ['场景', '原画', '华容道', '峭壁', '气氛图']
  },
  {
    id: 'asset-13',
    name: '【角色】貂蝉美人连环全身锦绣礼服立绘',
    category: AssetCategory.CharConcept,
    format: 'PSD',
    sizeMB: 45.1,
    thumbnail: 'https://images.unsplash.com/photo-1518156677180-95a2893f3e9f?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1518156677180-95a2893f3e9f?w=1000&auto=format&fit=crop&q=80',
    author: '2D_Lead_Zhao',
    platform: '美术资源库V2',
    desc: '貂蝉国色天香盛宴红装的高分辨率美术原画PSD源文件，包含完整的多图层拆分机制。',
    tags: ['角色', '原画', '立绘', '貂蝉', 'PSD']
  },
  {
    id: 'asset-14',
    name: '【武器】吕布方天画戟重金属次世代模型',
    category: AssetCategory.CharModel,
    format: 'OBJ',
    sizeMB: 88.5,
    thumbnail: 'https://images.unsplash.com/photo-1584281729155-3d5f30e69818?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1584281729155-3d5f30e69818?w=1000&auto=format&fit=crop&q=80',
    author: 'Model_TA_Li',
    platform: 'DCC共享端',
    desc: '方天画戟次世代高精雕刻OBJ。整合双月牙神雕细孔，含完整金属手绘划痕纹理。',
    tags: ['模型', '武器', '高模', '吕布', '划痕']
  },
  {
    id: 'asset-15',
    name: '【场景】草船借箭夜色江雾流体力学Blender档',
    category: AssetCategory.SceneModel,
    format: 'blend',
    sizeMB: 210.0,
    thumbnail: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1000&auto=format&fit=crop&q=80',
    author: 'Scene_Art_Wang',
    platform: 'DCC共享端',
    desc: '江上浓雾草船穿行Blender物理演示。内含预烘焙的烟雾气流动效与体积光粒子。',
    tags: ['场景', 'Blender', '草船借箭', '体积光', '水上雾']
  },
  {
    id: 'asset-16',
    name: '【动作】刺客职业高难度伏击瞬杀刺击动画',
    category: AssetCategory.Animation,
    format: 'FBX',
    sizeMB: 12.4,
    thumbnail: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1000&auto=format&fit=crop&q=80',
    author: 'Anim_Studio_A',
    platform: 'IT动画源文件',
    desc: '死士刺客跳跃倒立一击必杀动作。含前摇动作、爆发瞬间和落地潇洒收剑受击硬直。',
    tags: ['动画', '动作', '刺客', '战斗', 'FBX']
  },
  {
    id: 'asset-17',
    name: '【GUI】国风金镶玉极简按钮与通用面板UI',
    category: AssetCategory.GUI,
    format: 'PNG',
    sizeMB: 4.3,
    thumbnail: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=1000&auto=format&fit=crop&q=80',
    author: 'GUI_Sun',
    platform: 'GUI规范输出库',
    desc: '高质感纯手绘金镶玉石UI框架，适用于大型RPG系统的装备升级和属性强化弹窗。',
    tags: ['GUI', '界面', '国风', '金镶玉', '按钮']
  },
  {
    id: 'asset-18',
    name: '【特效】沙场风卷黄沙与尘土扬幕序列视频',
    category: AssetCategory.Video,
    format: 'MP4',
    sizeMB: 48.0,
    thumbnail: 'https://images.unsplash.com/photo-1520113548215-4b365023a2d4?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1520113548215-4b365023a2d4?w=1000&auto=format&fit=crop&q=80',
    author: 'VFX_LaoXie',
    platform: '特效序列中心',
    desc: '实景慢动作沙尘爆燃流体特效透明预合成通道，供制作组在DCC中叠加场景。',
    tags: ['特效', '视频', '沙暴', '沙场']
  },
  {
    id: 'asset-19',
    name: '【场景】桃花源仙境水墨花瓣掉落粒子高模',
    category: AssetCategory.SceneModel,
    format: 'PNG',
    sizeMB: 25.2,
    thumbnail: 'https://images.unsplash.com/photo-1490730141103-6cac27aaab94?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1490730141103-6cac27aaab94?w=1000&auto=format&fit=crop&q=80',
    author: 'Model_TA_Li',
    platform: 'DCC共享端',
    desc: '手统绘制高像素水墨桃花花半粒子，预置多样飘落受力倾斜轨迹和阴影匹配模式。',
    tags: ['场景', '桃花山庄', '粒子', '水墨风']
  },
  {
    id: 'asset-20',
    name: '【角色】曹操魏武王乱世暗金龙袍高精FBX',
    category: AssetCategory.CharModel,
    format: 'FBX',
    sizeMB: 110.5,
    thumbnail: 'https://images.unsplash.com/photo-1580136579312-94651dfd596d?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1580136579312-94651dfd596d?w=1000&auto=format&fit=crop&q=80',
    author: 'Model_A_Chen',
    platform: 'DCC共享端',
    desc: '曹阿瞒重臣长毛金镶暗红长袍，带有重物理贴图，支持布料力学骨骼，细节无懈可击。',
    tags: ['模型', '角色', '曹操', '魏武王', '龙袍']
  },
  {
    id: 'asset-21',
    name: '【角色】诸葛亮太极墨道袍原画概念切片',
    category: AssetCategory.CharConcept,
    format: 'PNG',
    sizeMB: 19.3,
    thumbnail: 'https://images.unsplash.com/photo-1569336415962-a4bd9f69cd83?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1569336415962-a4bd9f69cd83?w=1000&auto=format&fit=crop&q=80',
    author: '2D_Lead_Zhao',
    platform: '美术资源库V2',
    desc: '卧龙先生诸葛孔明主打太极八卦墨蓝丝线道袍原画。包含玉羽扇高光材质设定细节。',
    tags: ['角色', '原画', '诸葛亮', '卧龙', '太极']
  },
  {
    id: 'asset-22',
    name: '【场景】诸葛亮八阵图虚空石柱漂浮气氛图',
    category: AssetCategory.SceneConcept,
    format: 'JPG',
    sizeMB: 31.4,
    thumbnail: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=1000&auto=format&fit=crop&q=80',
    author: '2D_Env_Zhang',
    platform: '美术资源库V2',
    desc: '古战场诡秘阵法八阵图，石碑、古石柱悬浮于沙雾旋涡的气氛大图。汉字篆刻泛光点缀。',
    tags: ['场景', '原画', '气氛图', '八阵图', '阵法']
  },
  {
    id: 'asset-23',
    name: '【GUI】复古枯木纹与老牛皮纸战略征战地图',
    category: AssetCategory.GUI,
    format: 'PNG',
    sizeMB: 9.8,
    thumbnail: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?w=1000&auto=format&fit=crop&q=80',
    author: 'GUI_Sun',
    platform: 'GUI规范输出库',
    desc: '三国全境战略沙盘极品老旧皮卷地图背景，带有点亮城池、路线连线的整套UI样式。',
    tags: ['GUI', '界面', '沙盘', '地图', '复古']
  },
  {
    id: 'asset-24',
    name: '【动作】骑乘状态大戟倒摔击飞人仰马翻FBX',
    category: AssetCategory.Animation,
    format: 'FBX',
    sizeMB: 22.1,
    thumbnail: 'https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?w=1000&auto=format&fit=crop&q=80',
    author: 'Anim_Studio_A',
    platform: 'IT动画源文件',
    desc: '模拟重型长武器把骑兵拉下马的高级动力学反向动画，双马避让受击曲线。',
    tags: ['动画', '动作', '骑乘', '落马', '重置']
  },
  {
    id: 'asset-25',
    name: '【特效】火烧连营巨幅烈火腾升与滚滚狂澜裂爆',
    category: AssetCategory.Video,
    format: 'MP4',
    sizeMB: 150.2,
    thumbnail: 'https://images.unsplash.com/photo-1517089596392-db9a5e062af1?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1517089596392-db9a5e062af1?w=1000&auto=format&fit=crop&q=80',
    author: 'VFX_LaoXie',
    platform: '特效序列中心',
    desc: '极高对比度火海流体解算烘焙切片，烟硝、火星飞溅细节极高，主要贴付于船体材质。',
    tags: ['特效', '视频', '火焰', '赤壁火']
  },
  {
    id: 'asset-26',
    name: '【角色】张飞巨斧般的丈八蛇爪物理雕刻',
    category: AssetCategory.CharModel,
    format: 'OBJ',
    sizeMB: 72.1,
    thumbnail: 'https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?w=1000&auto=format&fit=crop&q=80',
    author: 'Model_TA_Li',
    platform: 'DCC共享端',
    desc: '丈八蛇矛环状黑金雕铸。3D高模拓扑，纹理极度狂野嗜血，附带物理锈迹。',
    tags: ['模型', '武器', '张飞', '丈八蛇矛']
  },
  {
    id: 'asset-27',
    name: '【场景】长坂桥纯古木裂纹力学损伤Maya档',
    category: AssetCategory.SceneModel,
    format: 'ma',
    sizeMB: 58.4,
    thumbnail: 'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=1000&auto=format&fit=crop&q=80',
    author: 'AnimTech_Yuan',
    platform: 'IT动画源文件',
    desc: '长坂坡古木桥，支持受击一键发生断裂下坠的约束层设定Maya工程。',
    tags: ['场景', 'Maya', '长坂坡', '木桥', '损伤断裂']
  },
  {
    id: 'asset-28',
    name: '【GUI】排兵布阵英雄将领对决数值属性底盘',
    category: AssetCategory.GUI,
    format: 'PNG',
    sizeMB: 3.1,
    thumbnail: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1000&auto=format&fit=crop&q=80',
    author: 'GUI_Sun',
    platform: 'GUI规范输出库',
    desc: '极富科技感同古风中式美学碰撞的英雄属性显示板，带有精美图腾雕花。',
    tags: ['GUI', '面板', '排兵布阵', '玉扣']
  },
  {
    id: 'asset-29',
    name: '【动作】诸葛亮挥羽扇运筹帷幄施法循环',
    category: AssetCategory.Animation,
    format: 'FBX',
    sizeMB: 8.9,
    thumbnail: 'https://images.unsplash.com/photo-1519074069444-1ba4e6663104?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1519074069444-1ba4e6663104?w=1000&auto=format&fit=crop&q=80',
    author: 'Anim_Studio_A',
    platform: 'IT动画源文件',
    desc: '卧龙法师羽扇高扬、披袍飘展施展东风烈阵的待机呼吸与吟唱高拟真姿势。',
    tags: ['动画', '动作', '诸葛亮', '施法', '羽扇']
  },
  {
    id: 'asset-30',
    name: '【角色】孙尚香翎羽弓红丝红裙英姿原画',
    category: AssetCategory.CharConcept,
    format: 'JPG',
    sizeMB: 11.2,
    thumbnail: 'https://images.unsplash.com/photo-1551269901-5c5e14c25df7?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1551269901-5c5e14c25df7?w=1000&auto=format&fit=crop&q=80',
    author: '2D_Lead_Zhao',
    platform: '美术资源库V2',
    desc: '枭姬孙尚香概念英挺弓手展示立绘。全身皮甲勾络，红翎冠随风律动。',
    tags: ['角色', '原画', '孙尚香', '弓箭手', '英姿']
  },
  {
    id: 'asset-31',
    name: '【场景】东吴柴桑深港水寨巨杉哨塔木料模型',
    category: AssetCategory.SceneModel,
    format: 'FBX',
    sizeMB: 134.0,
    thumbnail: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=1000&auto=format&fit=crop&q=80',
    author: 'Scene_Art_Wang',
    platform: 'DCC共享端',
    desc: '东吴长江水塞沿江防御瞭望塔FBX高分辨率粗糙木纹贴图。配有系缆绳索锁环细节。',
    tags: ['场景', '防御塔', '瞭望塔', '水寨', '木构']
  },
  {
    id: 'asset-32',
    name: '【角色】周瑜赤壁风云红羽氅轻皮战袍模型',
    category: AssetCategory.CharModel,
    format: 'FBX',
    sizeMB: 94.2,
    thumbnail: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=1000&auto=format&fit=crop&q=80',
    author: 'Model_A_Chen',
    platform: 'DCC共享端',
    desc: '美周郎周公瑾御敌高毛红领斗篷轻型铠甲模型。包含完整雕花金属肩甲及银饰扣。',
    tags: ['模型', '角色', '周瑜', '红领斗篷', '美周郎']
  },
  {
    id: 'asset-33',
    name: '【特效】江河波浪法线流动涟漪实时序列帧',
    category: AssetCategory.Video,
    format: 'MP4',
    sizeMB: 33.4,
    thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1000&auto=format&fit=crop&q=80',
    author: 'VFX_LaoXie',
    platform: '特效序列中心',
    desc: '高质量无缝循环的水面反射风噪与波动法线纹理叠加图，加速在Unreal / DCC中的制作。',
    tags: ['特效', '视频', '水流', '波浪纹理']
  },
  {
    id: 'asset-34',
    name: '【GUI】国潮锦鲤游祥云包夹关卡卡槽华丽边框',
    category: AssetCategory.GUI,
    format: 'PSD',
    sizeMB: 28.5,
    thumbnail: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=1000&auto=format&fit=crop&q=80',
    author: 'GUI_Sun',
    platform: 'GUI规范输出库',
    desc: '双赤锦鲤环绕池面浮雕般精雕细凿的限时活动卡框PSD，带云烟水墨图层。',
    tags: ['GUI', '界面', '卡牌边框', '锦鲤', 'PSD']
  },
  {
    id: 'asset-35',
    name: '【场景】许昌丞相府极寒飘雪冰宫气氛原画',
    category: AssetCategory.SceneConcept,
    format: 'JPG',
    sizeMB: 22.0,
    thumbnail: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?w=1000&auto=format&fit=crop&q=80',
    author: '2D_Env_Zhang',
    platform: '美术资源库V2',
    desc: '丞相府巍巍高耸，黑漆重门上积存厚雪的阴冷气氛概念，彰显乱世霸者宫廷沉重感。',
    tags: ['场景', '原画', '丞相府', '风雪', '气氛图']
  },
  {
    id: 'asset-36',
    name: '【动作】武将双劈砍旋风突进极高杀伤连招录',
    category: AssetCategory.Animation,
    format: 'FBX',
    sizeMB: 42.1,
    thumbnail: 'https://images.unsplash.com/photo-1508962914676-134849a727f0?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1508962914676-134849a727f0?w=1000&auto=format&fit=crop&q=80',
    author: 'Anim_Studio_A',
    platform: 'IT动画源文件',
    desc: '双持双锋重劈两下后，以旋风之势踏前斩击的极流畅格斗骨骼动画曲线。',
    tags: ['动画', '动作', '连招', '重伤', '爆发力']
  },
  {
    id: 'asset-37',
    name: '【角色】大乔锦鲤粉绣全身高洁立绘设计',
    category: AssetCategory.CharConcept,
    format: 'PNG',
    sizeMB: 16.5,
    thumbnail: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=1000&auto=format&fit=crop&q=80',
    author: '2D_Lead_Zhao',
    platform: '美术资源库V2',
    desc: '江南绝色大乔手绘概念立绘。水粉丝绸长裙，含水灯饰品及五环发簪线稿。',
    tags: ['角色', '原画', '大乔', '粉装', '江南']
  },
  {
    id: 'asset-38',
    name: '【场景】荆州古关隘重型木牙攻城抛石机拓扑',
    category: AssetCategory.SceneModel,
    format: 'OBJ',
    sizeMB: 105.4,
    thumbnail: 'https://images.unsplash.com/photo-1519003722822-6804797be889?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1519003722822-6804797be889?w=1000&auto=format&fit=crop&q=80',
    author: 'Model_TA_Li',
    platform: 'DCC共享端',
    desc: '三国古代超巨型原始铁骨抛石弩高模立体OBJ，滑轮绳索细节皆备，结构极其硬朗。',
    tags: ['场景', '攻城车', '抛石机', '高模']
  },
  {
    id: 'asset-39',
    name: '【角色】小乔真丝团扇精细面部手绘贴图包',
    category: AssetCategory.CharModel,
    format: 'TGA',
    sizeMB: 51.2,
    thumbnail: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=1000&auto=format&fit=crop&q=80',
    author: 'Model_A_Chen',
    platform: 'DCC共享端',
    desc: '小乔团扇清丽风格高分辨率手绘法线、金属度、AO以及漫反射贴图（4K超高画质真采）。',
    tags: ['模型', '贴图', '小乔', '法线贴图']
  },
  {
    id: 'asset-40',
    name: '【特效】翠竹林绿飘叶太极回旋风暴粒子效果',
    category: AssetCategory.Video,
    format: 'MP4',
    sizeMB: 62.5,
    thumbnail: 'https://images.unsplash.com/photo-1470240731273-7821a6eeb6bd?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1470240731273-7821a6eeb6bd?w=1000&auto=format&fit=crop&q=80',
    author: 'VFX_LaoXie',
    platform: '特效序列中心',
    desc: '竹叶如暴风卷动的法线气流视频，适用于武将刺剑激荡空气、落叶太极风大范围招式。',
    tags: ['特效', '视频', '风眼', '竹叶', '国风太极']
  },
  {
    id: 'asset-41',
    name: '【GUI】武将主动奥义圆形雕刻紫铜框边饰',
    category: AssetCategory.GUI,
    format: 'PNG',
    sizeMB: 2.8,
    thumbnail: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=1000&auto=format&fit=crop&q=80',
    author: 'GUI_Sun',
    platform: 'GUI规范输出库',
    desc: '高质感微磨损紫铜质地龙图腾凹凸圆形按键外环，九宫格配置完成，专为终极大招设计。',
    tags: ['GUI', '界面', '按键框', '紫铜']
  },
  {
    id: 'asset-42',
    name: '【动作】潇洒双股短剑飞旋连插后抱功致意',
    category: AssetCategory.Animation,
    format: 'FBX',
    sizeMB: 13.9,
    thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1000&auto=format&fit=crop&q=80',
    author: 'Anim_Studio_A',
    platform: 'IT动画源文件',
    desc: '双股剑飞越身底劈回并挽剑花、抱拳行礼的动作序列。符合写实中原武侠仪态。',
    tags: ['动画', '动作', '抱拳', '武将礼']
  },
  {
    id: 'asset-43',
    name: '【角色】修罗吕布黑红尖骨重型狂战鳞盔设定',
    category: AssetCategory.CharConcept,
    format: 'PNG',
    sizeMB: 24.3,
    thumbnail: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=1000&auto=format&fit=crop&q=80',
    author: '2D_Lead_Zhao',
    platform: '美术资源库V2',
    desc: '战神吕布因煞气附身进入暴走状态下的修罗盔甲细节。黑红熔岩纹路，煞气特效外廓。',
    tags: ['角色', '原画', '修罗境', '吕布', '暴走']
  },
  {
    id: 'asset-44',
    name: '【场景】虎牢关下漫天黄沙焦土防御城石墩模型',
    category: AssetCategory.SceneModel,
    format: 'blend',
    sizeMB: 280.0,
    thumbnail: 'https://images.unsplash.com/photo-1536599018102-9f803c140fc1?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1536599018102-9f803c140fc1?w=1000&auto=format&fit=crop&q=80',
    author: 'Scene_Art_Wang',
    platform: 'DCC共享端',
    desc: '虎牢关前阻拦骑兵冲击的大型拒马木排和带石桩废墟地形，预烘焙了漫天灰尘特效。',
    tags: ['场景', 'Blender', '废墟', '拒马', '城防']
  },
  {
    id: 'asset-45',
    name: '【角色】董卓极度奢丽酒色金丝软垫龙榻FBX',
    category: AssetCategory.CharModel,
    format: 'FBX',
    sizeMB: 162.0,
    thumbnail: 'https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=1000&auto=format&fit=crop&q=80',
    author: 'Model_A_Chen',
    platform: 'DCC共享端',
    desc: '董胖贼白日贪享乐的华丽屏风卧榻高精度模型。包含丝绸软包、散落器血等次世代场景小道具。',
    tags: ['模型', '角色', '董卓', '奢华榻', '卧榻道具']
  },
  {
    id: 'asset-46',
    name: '【场景】八门金锁阵阴雨狂泥黄泥沙原画气氛图',
    category: AssetCategory.SceneConcept,
    format: 'JPG',
    sizeMB: 41.5,
    thumbnail: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1000&auto=format&fit=crop&q=80',
    author: '2D_Env_Zhang',
    platform: '美术资源库V2',
    desc: '阵核心生门、死门分叉点雨天泥泞沼泽战场景概念。通过黑沉死气和金色八卦符显露神怪色彩。',
    tags: ['场景', '原画', '气氛图', '阵法', '沼泽泥地']
  },
  {
    id: 'asset-47',
    name: '【GUI】国韵金缕墨道水墨卷轴动态伸缩UI',
    category: AssetCategory.GUI,
    format: 'PNG',
    sizeMB: 14.2,
    thumbnail: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=1000&auto=format&fit=crop&q=80',
    author: 'GUI_Sun',
    platform: 'GUI规范输出库',
    desc: '一键卷轴开合机制的战略面板及城池状态主展示面板UI切图包。墨染及金丝轮廓边缘。',
    tags: ['GUI', '界面', '动态卷轴', '金丝']
  },
  {
    id: 'asset-48',
    name: '【动作】双钢刀大旋风疯狂横扫大斩击反馈FBX',
    category: AssetCategory.Animation,
    format: 'FBX',
    sizeMB: 31.0,
    thumbnail: 'https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=1000&auto=format&fit=crop&q=80',
    author: 'Anim_Studio_A',
    platform: 'IT动画源文件',
    desc: '狂化先锋挥舞重双刃、踏冰碎地、疯狂绞杀的风噪轨迹动作解算。',
    tags: ['动画', '动作', '旋风斩', '狂战士']
  },
  {
    id: 'asset-49',
    name: '【特效】黄巾军幽灵死灰魂灯引路爆燃粒子视频',
    category: AssetCategory.Video,
    format: 'MP4',
    sizeMB: 88.2,
    thumbnail: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=1000&auto=format&fit=crop&q=80',
    author: 'VFX_LaoXie',
    platform: '特效序列中心',
    desc: '黄天当立秘术中，空中幽灵死火浮游、遭遇物理碎裂发生爆燃特效的黑罩通道视频。',
    tags: ['特效', '视频', '死火', '法术特效']
  },
  {
    id: 'asset-50',
    name: '【场景】博望坡粮草现场稻草垛物理高精度FBX',
    category: AssetCategory.SceneModel,
    format: 'FBX',
    sizeMB: 42.7,
    thumbnail: 'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=1000&auto=format&fit=crop&q=80',
    author: 'Model_TA_Li',
    platform: 'DCC共享端',
    desc: '博望坡荒坡专用草谷垛、围栏以及碎木柴，支持物理火烧后骨骼塌陷动效。',
    tags: ['场景', '粮草垛', '博望坡', '废弃物']
  },
  {
    id: 'asset-51',
    name: '【角色】司马懿鬼道狂士暗紫长袖大立绘',
    category: AssetCategory.CharConcept,
    format: 'PNG',
    sizeMB: 17.6,
    thumbnail: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1000&auto=format&fit=crop&q=80',
    author: '2D_Lead_Zhao',
    platform: '美术资源库V2',
    desc: '司马仲达黑羽鸦翅华服原画立绘。面庞阴深、手持白芒血珠，具有邪逸高贵感。',
    tags: ['角色', '原画', '司马懿', '鬼道', '主包']
  },
  {
    id: 'asset-52',
    name: '【角色】神射马超雪银亮片铠甲高精模型',
    category: AssetCategory.CharModel,
    format: 'FBX',
    sizeMB: 115.0,
    thumbnail: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1000&auto=format&fit=crop&q=80',
    author: 'Model_A_Chen',
    platform: 'DCC共享端',
    desc: '西凉马超亮银鳞片胸甲及飞雪披风FBX。含40万面，全身法线极度清晰整洁。',
    tags: ['模型', '角色', '马超', '西凉', '银甲']
  },
  {
    id: 'asset-53',
    name: '【场景】潼关岩石峭壁风化泥沙断崖一键地形',
    category: AssetCategory.SceneModel,
    format: 'OBJ',
    sizeMB: 195.4,
    thumbnail: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1000&auto=format&fit=crop&q=80',
    author: 'Scene_Art_Wang',
    platform: 'DCC共享端',
    desc: '潼关峡口断崖重型土石一键拉伸模型。包含深厚侵蚀断裂质感。支持法线融合。',
    tags: ['场景', 'OBJ', '断崖', '峭壁', '潼关']
  },
  {
    id: 'asset-54',
    name: '【动作】重铠狂斩受反击侧跳闪身接盾撞',
    category: AssetCategory.Animation,
    format: 'FBX',
    sizeMB: 19.8,
    thumbnail: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1000&auto=format&fit=crop&q=80',
    author: 'Anim_Studio_A',
    platform: 'IT动画源文件',
    desc: '武将近身冲突的高级位移动作。带全身偏斜滑步、左手推击和短跳翻滚。',
    tags: ['动画', '动作', '战法', '翻滚闪避']
  },
  {
    id: 'asset-55',
    name: '【GUI】金缕玉扣三国之战凯旋金光法阵UI',
    category: AssetCategory.GUI,
    format: 'PNG',
    sizeMB: 11.5,
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1000&auto=format&fit=crop&q=80',
    author: 'GUI_Sun',
    platform: 'GUI规范输出库',
    desc: '战役胜利、升级凯旋时的水墨飞溅加上金光绽开的全景动画切图组，包含高帧序列。',
    tags: ['GUI', '界面', '凯旋开屏', '金缕']
  },
  {
    id: 'asset-56',
    name: '【特效】长弓弓排箭雨万箭齐散射击流星轨迹',
    category: AssetCategory.Video,
    format: 'MP4',
    sizeMB: 112.0,
    thumbnail: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1000&auto=format&fit=crop&q=80',
    author: 'VFX_LaoXie',
    platform: '特效序列中心',
    desc: '攻城射箭时，漫天黑点般的锋芒尾烟抛物线视频合成序列。带有火流星特效版本。',
    tags: ['特效', '视频', '箭雨', '漫天箭']
  },
  {
    id: 'asset-57',
    name: '【场景】铜雀台高空朱瓦水榭廊桥奢美气氛图',
    category: AssetCategory.SceneConcept,
    format: 'JPG',
    sizeMB: 34.0,
    thumbnail: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1000&auto=format&fit=crop&q=80',
    author: '2D_Env_Zhang',
    platform: '美术资源库V2',
    desc: '曹操宴请群臣之铜雀台。主打夕阳余晖下，朱漆飞檐、两座副楼通过跨空木天桥连接的高空绝景。',
    tags: ['场景', '原画', '气氛图', '铜雀台', '廊桥']
  },
  {
    id: 'asset-58',
    name: '【角色】魏延狂古之狼骷髅白骨半面具刺客模型',
    category: AssetCategory.CharModel,
    format: 'FBX',
    sizeMB: 142.0,
    thumbnail: 'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=1000&auto=format&fit=crop&q=80',
    author: 'Model_A_Chen',
    platform: 'DCC共享端',
    desc: '魏延次世代高精尖刺铁衣及野狼额骨骷髅半面具高模。细节狂野，非常适合潜行格斗。',
    tags: ['模型', '角色', '魏延', '刺客', '骷髅面具']
  },
  {
    id: 'asset-59',
    name: '【动作】双手穿梭重短弩腾跃翻腾连发回手轻功',
    category: AssetCategory.Animation,
    format: 'FBX',
    sizeMB: 26.5,
    thumbnail: 'https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=1000&auto=format&fit=crop&q=80',
    author: 'Anim_Studio_A',
    platform: 'IT动画源文件',
    desc: '敏捷性武将空中翻身两次，向左右斜下方各连续射击弩箭并后空翻平稳下坠的动作。',
    tags: ['动画', '动作', '空翻', '弩箭手', '特技']
  },
  {
    id: 'asset-60',
    name: '【角色】孟获蛮王南蛮巨型图腾猛犸象骨锤',
    category: AssetCategory.CharModel,
    format: 'blend',
    sizeMB: 185.0,
    thumbnail: 'https://images.unsplash.com/photo-1595152772835-219674b2a8a6?w=400&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1595152772835-219674b2a8a6?w=1000&auto=format&fit=crop&q=80',
    author: 'Model_TA_Li',
    platform: 'DCC共享端',
    desc: '南蛮王孟获雕琢百兽图腾猛角象牙锤Blender场景及资产。具有原始石料及骨纹的强PBR刻画。',
    tags: ['模型', '武器', '孟获', '图腾柱', 'Blender']
  }
];

